/** Shared constants used across fighter-facing and admin pages */

export const SPORTS = [
  "MMA",
  "Boxing",
  "Muay Thai",
  "Brazilian Jiu-Jitsu",
  "Wrestling",
  "Kickboxing",
  "Bare Knuckle",
  "Karate",
  "Judo",
  "Taekwondo",
  "Personal Trainer",
  "Coach",
] as const;

export const COUNTRIES = [
  "Argentina",
  "Australia",
  "Brazil",
  "Cameroon",
  "Canada",
  "China",
  "Colombia",
  "Cuba",
  "France",
  "Germany",
  "India",
  "Ireland",
  "Italy",
  "Japan",
  "Kazakhstan",
  "Mexico",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Philippines",
  "Poland",
  "Russia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Thailand",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Uzbekistan",
  "Other",
] as const;
