project_id = "mhmoxwmxnojljehbigtp"

[functions.send-notification]
verify_jwt = false

[functions.receive-sale-webhook]
verify_jwt = false

[functions.generate-landing-image]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.firecrawl-scrape-product]
verify_jwt = false

[functions.import-product-feed]
verify_jwt = false

[functions.sync-fmtc-products]
verify_jwt = false

[functions.sync-sovrn-products]
verify_jwt = false

[functions.sovrn-reporting]
verify_jwt = false

[functions.sync-sovrn-merchants]
verify_jwt = false

[functions.firecrawl-map-site]
verify_jwt = false
